name: flutter_zoom_box
description: A box that makes widgets inside zoomable.
version: 0.1.0
author: Daehyeon <ndh8392@gmail.com>
homepage: https://daehyeonnam.github.io
repository: https://github.com/DaeHyeonNam/flutter_zoom_box

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
